show databases;
create database payroll_services;
show databases;
use payroll_services;
create table employee_payroll(id int not null auto_increment, name varchar(50) not null,salary Double not null,startDate Date not null, primary key(id) );
describe employee_payroll;
insert into employee_payroll(name,salary,startDate)values('Javul',10000,'2022-01-01');
insert into employee_payroll(name,salary,startDate)values('Akash',20000,'2022-02-02');
insert into employee_payroll(name,salary,startDate)values('Praveen',30000,'2022-03-03');
insert into employee_payroll(name,salary,startDate)values('Naman',40000,'2022-04-04');
select * from employee_payroll;
select * from employee_payroll where salary > 30000;
select * from employee_payroll where startDate between '2022-03-01' AND Date(now());
alter table employee_payroll add gender char not null;
update employee_payroll set gender = 'M' where id>0;
select count(*) from salary;
select max(salary) as max, sum(salary),avg(salary) from employee_payroll;